---
baseURL: https://mycoscaffold.com/
languageCode: en-us
title: Myco Scaffold Inc.
theme: piko
paginate: "9"
copyright: Built with [Piko](https://github.com/heksagonnet/piko)
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
font-stencil: 'https://fonts.googleapis.com/css2?family=Stick+No+Bills&display=swap'
google_fonts: [
    ["Fira Code", "400, 700"],
    ["Open Sans", "400, 400i, 700, 700i"]
  ]
heading_font: "Fira Code"
body_font: "Open Sans"

outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: G-73VZ1Y0ZQ5
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Michael
  description: We are a full service scaffold company. Residential, commercial, and industrial, and specialty applications serving the greater Sacramento area.
  email: "sales@mycoscaffold.com"
  phoneNumber: 916-538-1551
  contractorsLicense: 1121193
  social:
    instagram: 
      icon: /uploads/icon-ig.png
      url: https://www.instagram.com/myco_scaffold/
    facebook:       
      icon: /uploads/icon-fb.svg
      url: https://www.facebook.com/profile.php?id=61554024987180
  PhotoAttrText:
  PhotoAttrUrl:
  math: false
  theme:
    colors:
      primary: --muted-color
      contrast: --contrast-outline
  images:
  - "/uploads/og.webp"
  label:
    title: MycoScaffold
    text: MycoScaffold
    lightNavIcon: /uploads/logo-100x130.png
    darkNavIcon: /uploads/logo-100x130.png
    iconHeight: "35"
    iconWIdth: "35"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: /uploads/favicon.svg
    favicon16x16: /uploads/favicon.svg
    favicon32x32: /uploads/favicon.svg
    apple_touch_icon: /uploads/zap.svg
    safari_pinned_tab: /uploads/zap.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: Myco Scaffold
    heroDescription: We are a full service scaffold company. Residential, commercial, and industrial, and specialty applications serving the greater Sacramento area.
    heroCTAPrimaryText: Get a Quote
    heroCTAPrimaryUrl: "/quote/"
    heroCTASecondaryText: Contact
    heroCTASecondaryUrl: "/contact/"
    heroCTAImage: "/uploads/logo-500x649.png"
    heroCTAImageAltText: "The Myco Scaffold Inc. Logo. A man holding up scaffolding and the globe."
    heroBackgroundImage: "/uploads/"
    # Blog Section
    disableBlogSection: false
    blogTitle: Latest Posts
    blogDescription: This is my latest blog posts
    seeMoreText: More Posts
    # About Section    
    disableAboutSection: false
    aboutTitle: About
    aboutDescription: 
    aboutImgUrl: "/uploads/logo-500x649.png"
    aboutContent: At Myco Scaffold, we are not just a business; we are the legacy of a family that has been the backbone of construction projects across Sacramento and Northern California for three generations. We forge enduring relationships that stand the test of time, much like the structures we help to build. Our clients don't just see us as a provider; they see us as a partner in progress, elevating their projects with meticulous care and an unwavering commitment to safety.
    # Portfolio Section
    disablePortfolioSection: false
    portfolioTitle: Portfolio
    portfolioDescription: Some of my works
    portfolio:
    - imageUrl: /uploads/portfolio-1.webp
      alt: # image alt for better SEO
      description: Portfolio One.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-2.webp
      alt: # image alt for better SEO
      description: Portfolio Two.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-3.webp
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
  # pages
  servicespage:
    name: Quote
    url: "/services"
    title: Services
    description: --------------------
    headerImageUrl: /uploads/headerImageQuote.webp
    headerImageAltText: "Two people meeting with blueprints on the table and one of them is using a calculator."
    PhotoAttrText: Photo by Pixabay
    PhotoAttrUrl: https://www.pexels.com/photo/three-people-sitting-beside-table-416405/
# pages
  quotepage:
    name: Quote
    url: "/quote"
    title: Request a Quote
    description: The best way to start your project is requesting a free quote
    headerImageUrl: /uploads/headerImageQuote.webp
    headerImageAltText: "Two people meeting with blueprints on the table and one of them is using a calculator."
    PhotoAttrText: Photo by Pixabay
    PhotoAttrUrl: https://www.pexels.com/photo/three-people-sitting-beside-table-416405/
    # pages
  contactpage:
    name: Quote
    url: "/contact"
    title: Quote
    description: Let's figure this out together
    headerImageUrl: /uploads/headerImageContact.webp
    headerImageAltText: 
    PhotoAttrText: Photo by Anete Lusina
    PhotoAttrUrl: https://www.pexels.com/photo/instruments-prepared-for-measurements-in-house-4792479/
    # pages 
  careerspage:
    name: Careers
    url: "/careers"
    title: Career with Myco Scaffold
    description: Lets build together.
    headerImageUrl: /uploads/headerImageContact.webp
    headerImageAltText: 
    PhotoAttrText: Photo by Anete Lusina
    PhotoAttrUrl: https://www.pexels.com/photo/instruments-prepared-for-measurements-in-house-4792479/


menus:
  main: # Main Menu
  - name: Services
    title: Services
    pre: tool
    url: "/services"
    weight: "10"
  - name: Quote
    title: Quote
    pre: file-text
    url: "/quote"
    weight: "20"
  - name: Careers
    title: Careers
    pre: file-text
    url: "/careers"
    weight: "30"
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "40"
